### ISSUE TITLE
Turn off Postgres ssl in new docker image

### ISSUE THREAD

**Issue by ThisIsQasim** [papercups-io/papercups#596]
**Describe the bug**
The new docker images requires ssl for connecting to postgres. Can you make it configurable?

**Comment by cheeseblubber** [comment]
Hi @ThisIsQasim can you describe your environment how are you deploying to the postgres and what the error you are getting. Why do you want to disable SSL for connecting to Postgres?

**Comment by cheeseblubber** [comment]
Im leaning towards keeping ssl required for prod docker file postgres and keeping it optional for dev dockerfile. I guess it would make sense for testing purposes or side projects

**Comment by ThisIsQasim** [comment]
Papercups and postgres are in a private network so adding TLS on top seems a little extra. The postgres is shared with another application which doesn't like TLS so enabling TLS is not an option for me. I would really appreciate if TLS for the database could be turned off by setting an environment variable. You could have it enabled by default of course.

**Comment by cheeseblubber** [comment]
Fair point I've merged it in the environment variable is "REQUIRE_DB_SSL"

**Comment by ThisIsQasim** [comment]
Setting the environment variable `REQUIRE_DB_SSL=false` still expects ssl. Is it because environment variables are treated as strings and the config expects a boolean?

**Comment by cheeseblubber** [comment]
Oops good catch. I've fixed it in the latest master should be building soon

**Comment by ThisIsQasim** [comment]
Thank you for the prompt response but for some reason it is still expecting SSL on the database. Maybe I am doing something wrong. Will try in a fresh environment and see if that makes a difference.

**Comment by cheeseblubber** [comment]
Did you get to try on a fresh environment?

**Comment by knewter** [comment]
This still doesn't work because it's a compile-time ENV var so the container for papercups was built with it enabled and this doesn't provide a way to override it generally. There's a nice post on configuration in elixir with releases here: https://elixir-lang.org/getting-started/mix-otp/config-and-releases.html

It should probably be present in this file to support runtime changes: https://github.com/papercups-io/papercups/blob/master/config/releases.exs

**Comment by knewter** [comment]
(on a related note, I landed here because I'm working on adding papercups to homelabos - https://gitlab.com/NickBusey/HomelabOS/-/merge_requests/654)

**Comment by cheeseblubber** [comment]
Yep that is the issue I've created to migrate phoneix over next week https://github.com/papercups-io/papercups/issues/624

**Comment by reichert621** [comment]
@cheeseblubber is this still an issue or can we close?

**Comment by cheeseblubber** [comment]
Closing now this is fixed
